// <auto-generated />
namespace Hospital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_treatment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_treatment));
        
        string IMigrationMetadata.Id
        {
            get { return "201604251222432_Added_treatment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
